[package]
name = "image-service"
version = "0.1.0"
authors = ["Ilya Kopeshtianski <lupusanay@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "^1.0.5"
actix-multipart = "^0.1.2"
image = "^0.22.1"
env_logger = "^0.6.2"
futures = "0.1.28"