[package]
name = "blog"
version = "0.1.0"
authors = ["Ilya Kopeshtianski <lupusanay@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "2.0"
actix-rt = "1.0"
env_logger = "0.7"
futures = "0.3"
serde = "1.0"